<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="hr" xml:lang="hr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matea Topić Crnoja">
<meta name="author" content="izv. prof. dr. sc. Petra Palić">
<meta name="author" content="doc. dr. sc. Luka Šikić">
<meta name="keywords" content="religijski turizam, digitalni mediji, memorijalni okvir, strukturalni model tema, Hrvatska, računalna društvena znanost">

<title>Memorijalni okvir kao treći registar u medijskoj reprezentaciji hrvatskih marijanskih i drugih katoličkih odredišta (2021.–2024.)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="manuscript_one_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_one_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_one_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_one_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_one_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_one_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_one_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_one_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_one_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_one_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_one_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#uvod" id="toc-uvod" class="nav-link active" data-scroll-target="#uvod"><span class="header-section-number">1</span> Uvod</a></li>
  <li><a href="#pregled-literature" id="toc-pregled-literature" class="nav-link" data-scroll-target="#pregled-literature"><span class="header-section-number">2</span> Pregled literature</a>
  <ul class="collapse">
  <li><a href="#definicija-religijskog-turizma" id="toc-definicija-religijskog-turizma" class="nav-link" data-scroll-target="#definicija-religijskog-turizma"><span class="header-section-number">2.1</span> Definicija religijskog turizma</a></li>
  <li><a href="#relevantnost-istraživačkih-pitanja" id="toc-relevantnost-istraživačkih-pitanja" class="nav-link" data-scroll-target="#relevantnost-istraživačkih-pitanja"><span class="header-section-number">2.2</span> Relevantnost istraživačkih pitanja</a>
  <ul class="collapse">
  <li><a href="#frekvencija-medijskog-spominjanja" id="toc-frekvencija-medijskog-spominjanja" class="nav-link" data-scroll-target="#frekvencija-medijskog-spominjanja"><span class="header-section-number">2.2.1</span> Frekvencija medijskog spominjanja</a></li>
  <li><a href="#kontekst-i-ton-spominjanja" id="toc-kontekst-i-ton-spominjanja" class="nav-link" data-scroll-target="#kontekst-i-ton-spominjanja"><span class="header-section-number">2.2.2</span> Kontekst i ton spominjanja</a></li>
  <li><a href="#sezonalnost-medijskih-objava" id="toc-sezonalnost-medijskih-objava" class="nav-link" data-scroll-target="#sezonalnost-medijskih-objava"><span class="header-section-number">2.2.3</span> Sezonalnost medijskih objava</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#podaci-i-metode" id="toc-podaci-i-metode" class="nav-link" data-scroll-target="#podaci-i-metode"><span class="header-section-number">3</span> Podaci i metode</a>
  <ul class="collapse">
  <li><a href="#istraživački-dizajn" id="toc-istraživački-dizajn" class="nav-link" data-scroll-target="#istraživački-dizajn"><span class="header-section-number">3.1</span> Istraživački dizajn</a></li>
  <li><a href="#izvor-podataka-i-konstrukcija-korpusa" id="toc-izvor-podataka-i-konstrukcija-korpusa" class="nav-link" data-scroll-target="#izvor-podataka-i-konstrukcija-korpusa"><span class="header-section-number">3.2</span> Izvor podataka i konstrukcija korpusa</a></li>
  <li><a href="#označavanje-registara" id="toc-označavanje-registara" class="nav-link" data-scroll-target="#označavanje-registara"><span class="header-section-number">3.3</span> Označavanje registara</a></li>
  <li><a href="#analitički-postupci" id="toc-analitički-postupci" class="nav-link" data-scroll-target="#analitički-postupci"><span class="header-section-number">3.4</span> Analitički postupci</a></li>
  </ul></li>
  <li><a href="#rezultati" id="toc-rezultati" class="nav-link" data-scroll-target="#rezultati"><span class="header-section-number">4</span> Rezultati</a>
  <ul class="collapse">
  <li><a href="#tri-registra-umjesto-dva" id="toc-tri-registra-umjesto-dva" class="nav-link" data-scroll-target="#tri-registra-umjesto-dva"><span class="header-section-number">4.1</span> Tri registra umjesto dva</a></li>
  <li><a href="#geografija-memorijalnog-okvira" id="toc-geografija-memorijalnog-okvira" class="nav-link" data-scroll-target="#geografija-memorijalnog-okvira"><span class="header-section-number">4.2</span> Geografija memorijalnog okvira</a></li>
  <li><a href="#sec-orthogonality" id="toc-sec-orthogonality" class="nav-link" data-scroll-target="#sec-orthogonality"><span class="header-section-number">4.3</span> Konvergentna validnost rječničkih kategorija i induktivnih tema</a></li>
  <li><a href="#stabilnost-u-razdoblju-nakon-pandemije" id="toc-stabilnost-u-razdoblju-nakon-pandemije" class="nav-link" data-scroll-target="#stabilnost-u-razdoblju-nakon-pandemije"><span class="header-section-number">4.4</span> Stabilnost u razdoblju nakon pandemije</a></li>
  </ul></li>
  <li><a href="#rasprava" id="toc-rasprava" class="nav-link" data-scroll-target="#rasprava"><span class="header-section-number">5</span> Rasprava</a></li>
  <li><a href="#zaključak" id="toc-zaključak" class="nav-link" data-scroll-target="#zaključak"><span class="header-section-number">6</span> Zaključak</a></li>
  <li><a href="#literatura" id="toc-literatura" class="nav-link" data-scroll-target="#literatura">Literatura</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript_one.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="manuscript_one.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Memorijalni okvir kao treći registar u medijskoj reprezentaciji hrvatskih marijanskih i drugih katoličkih odredišta (2021.–2024.)</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Matea Topić Crnoja </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Odjel za sociologiju, Hrvatsko katoličko sveučilište
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">izv. prof. dr. sc. Petra Palić </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Odjel za sociologiju, Hrvatsko katoličko sveučilište
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">doc. dr. sc. Luka Šikić </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Odjel za sociologiju, Hrvatsko katoličko sveučilište
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">28. travnja 2026.</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>TBD – Croatian abstract.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>religijski turizam, digitalni mediji, memorijalni okvir, strukturalni model tema, Hrvatska, računalna društvena znanost</p>
  </div>
</div>

</header>


<section id="uvod" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Uvod</h1>
<p>Studije medijskog uokvirivanja religijskog turizma uobičajeno pretpostavljaju binarnu strukturu diskursa. Prvi je registar religijski i tretira svetište kao mjesto duhovnog iskustva. Drugi je registar turistički i gleda na svetište kao na destinaciju s ekonomskim profilom. Ta se pretpostavka eksplicitno reproducira u domaćoj literaturi (Duvnjak, Relja i Žeravica, 2011; Čavlek i sur., 2011), a empirijska istraživanja medijskog sadržaja tipično operacionaliziraju distinkciju kroz dva komplementarna leksička rječnika ili kroz dvodimenzionalan kontinuum između duhovnih i sekularnih motiva (Cohen, 1979; Smith, 1992; Collins-Kreiner, 2020). U ovom radu, na temelju računalne analize 13 921 medijskog članka o deset hrvatskih katoličkih odredišta objavljenih u razdoblju od siječnja 2021. do svibnja 2024., pokazujemo da binarni model sustavno previđa treći, kvantitativno značajan registar.</p>
<p>Petnaest posto članaka iz korpusa pripada registru koji nazivamo memorijalnim. Riječ je o diskursu u kojem su svetište, hodočašće ili katolički blagdan tematski povezani sa žrtvama, ratnim spomenom i kolektivnom traumom. Memorijalni je registar široko raspoređen po korpusu i prisutan u znatnoj mjeri na svim trima tipovima odredišta, no s izrazitom koncentracijom u jednome lokalitetu. U Voćinu, mjestu zapadnoslavonskog masakra iz prosinca 1991. godine, čak 42 % medijskih članaka pripada memorijalnom okviru, što je gotovo trostruko više od korpusnoga prosjeka. Iz toga proizlazi središnja teza ovog rada. Analitički okvir koji medijsko uokvirivanje katoličkih odredišta svodi na dijadu religijskog i turističkog sustavno krivo čita pokrivenost lokaliteta čija je liturgijska identitet posredovana sjećanjem na Domovinski rat.</p>
<p>Rad je strukturiran kako slijedi. U pregledu literature (§2) izlažemo dvostruku tradiciju definiranja religijskog turizma i obrazlažemo zašto memorijalni registar do sada nije bio analitički vidljiv. U §3 opisujemo korpus, tipologiju odredišta s tri kategorije (nacionalna marijanska svetišta, lokalna marijanska svetišta i nemarijanska katolička svetišta) te analitičke postupke koji uključuju rječničko označavanje registara, hi-kvadrat dekompoziciju, multinomijalnu logističku regresiju, strukturalni model tema i ručno kodiranje za vanjsku validaciju. U §4 prikazujemo četiri ključna nalaza. Prvi se odnosi na distribuciju triju registara u korpusu (§4.1), drugi na geografiju memorijalnog okvira po pojedinim odredištima (§4.2), treći na neovisnost induktivnog topičkog modela od rječničke klasifikacije (§4.3), a četvrti na stabilnost distribucije okvira u razdoblju od 2021. do 2024. unatoč pandemijskom prekidu (§4.4). U §5 raspravljamo implikacije nalaza za teoriju medijatizacije katolicizma u poslijeratnim društvima i za metodologiju računalne analize religijskog medijskog sadržaja.</p>
</section>
<section id="pregled-literature" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Pregled literature</h1>
<section id="definicija-religijskog-turizma" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="definicija-religijskog-turizma"><span class="header-section-number">2.1</span> Definicija religijskog turizma</h2>
<p>Pojam religijskog turizma u suvremenoj literaturi nije jednoznačan, pa se u radu mora eksplicitno zauzeti stav. Tri su ključne linije razgraničenja koje treba razriješiti prije nego se krene u empiriju.</p>
<p>Prvo razgraničenje tiče se odnosa hodočašća i religijskog turizma. Tradicionalna antropologija Turnera i Turnera (1978) te kasnija studija Eadea i Sallnowa (1991) tretirala je hodočašće kao ritualnu praksu čija je primarna svrha duhovna, a turizam kao praksu čija je svrha sekularna. Od Cohena (1979, 1992) i Smith (1992) ta se binarnost razgrađuje kroz ideju kontinuuma na kojemu se posjetitelj smješta između dvaju polova, od vjerskog putnika do sekularnog odmoraša. Collins-Kreiner (2020) zaključuje kako je to razlikovanje danas u praksi neodrživo jer motivi posjetitelja rutinski kombiniraju duhovne, kulturne i konzumne elemente.</p>
<p>Drugo razgraničenje odnosi se na pitanje motiva naspram prostora. Griffin i Raj (2018) predlažu operativnu definiciju po kojoj religijski turizam obuhvaća svaki oblik putovanja koji uključuje posjet svetištu, vjerskom objektu ili vjerskom događaju, bez obzira jesu li motivi putnika primarno religijski ili sekularni. Takva prostorna definicija rješava problem nepouzdanosti samoprijavljenih motiva i daje empirijski mjerljiv kriterij, što je metodološki važno jer u medijskim tekstovima rijetko je dostupan motivacijski podatak pojedinog posjetitelja.</p>
<p>Treće razgraničenje nudi hrvatska literatura. Duvnjak, Relja i Žeravica (2011) definiraju religijski turizam kao poseban segment turističke ponude koji se odvija u prostorima vjerskog značaja i u kojem su sadržaji duhovne, kulturne i hodočasničke prirode međusobno isprepleteni. Čavlek i suradnici (2011) naglašavaju njegovu ekonomsku funkciju konverzije neekonomskih dobara u ekonomska. Religijski turizam tako istodobno proizvodi duhovnu i ekonomsku vrijednost, što objašnjava zašto u njemu često postoji napetost između sakralnog i komercijalnog registra.</p>
<p>Za potrebe ovog rada predlaže se sljedeća radna definicija. Religijska turistička destinacija je prostor koji istodobno ispunjava dva kriterija. Prvi je da prostor funkcionira kao svetište, hodočasničko mjesto ili sakralni lokalitet s prepoznatim duhovnim i kulturno povijesnim značajem. Drugi je da je pozicioniran u turističkoj i medijskoj komunikaciji kao destinacija koja privlači posjetitelje s heterogenim motivima, od strogo vjerskih do pretežno kulturnih. U ovome se radu analizira medijska reprezentacija takvih destinacija u cijelosti, obuhvaćajući sve registre u kojima se one pojavljuju, kako bi se rekonstruirao njihov diskurzivni profil kao kombinacija sakralnog, turističkog, kulturnog, političkog i ostalih okvira.</p>
</section>
<section id="relevantnost-istraživačkih-pitanja" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="relevantnost-istraživačkih-pitanja"><span class="header-section-number">2.2</span> Relevantnost istraživačkih pitanja</h2>
<section id="frekvencija-medijskog-spominjanja" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="frekvencija-medijskog-spominjanja"><span class="header-section-number">2.2.1</span> Frekvencija medijskog spominjanja</h3>
<p>Frekvencijska analiza najjednostavnije je operacionalizirana komponenta, ali njezina je teorijska težina veća nego što se isprva čini. Mediji ne reflektiraju prostor podjednako, nego ga selektivno proizvode kao javno značajan. To što određene destinacije dominiraju medijskim prostorom nije puka empirijska činjenica nego izraz dugoročnih procesa postavljanja dnevnog reda (McCombs i Shaw, 1972) i institucionalne vidljivosti. Frekvencija je, drugim riječima, zamjenska mjera za ono što Couldry i Hepp (2017) nazivaju medijatiziranom prisutnošću, odnosno sposobnošću jednog prostora da uopće uđe u javnu komunikacijsku sferu. Za hrvatski kontekst ovo pitanje ima dodatnu vrijednost jer postoji zanimljiv nesrazmjer između crkveno simboličkog statusa pojedinog svetišta i njegove medijske vidljivosti.</p>
</section>
<section id="kontekst-i-ton-spominjanja" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="kontekst-i-ton-spominjanja"><span class="header-section-number">2.2.2</span> Kontekst i ton spominjanja</h3>
<p>Kontekst i ton spominjanja ono je što u komunikologiji nazivamo okvirom. Entman (1993) definira okvir kao selekciju određenih aspekata neke stvarnosti i njihovo isticanje u komunikacijskom tekstu na način koji promiče određenu definiciju problema, uzročnu interpretaciju, moralnu procjenu ili preporuku djelovanja. Za religijska svetišta to znači da isti prostor može biti uokviren kao duhovno središte, turistička atrakcija, kulturno heritažno mjesto, politički simbol, folklorna pozornica ili mjesto skandala. Izbor okvira bitno određuje kako publika procesira poruku i kakvu turističku odluku potencijalno donosi. Pavić, Kurbanović i Levak (2017) u hrvatskom kontekstu pokazuju da medijatizacija katolicizma u Hrvatskoj ne donosi nove interpretacije doktrina, ali redefinira način na koji se crkveni prostori i događaji prezentiraju javnosti.</p>
</section>
<section id="sezonalnost-medijskih-objava" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="sezonalnost-medijskih-objava"><span class="header-section-number">2.2.3</span> Sezonalnost medijskih objava</h3>
<p>Sezonalnost je teorijski zanimljiva iz dva razloga. Operativno, religijski turizam u Hrvatskoj odvija se oko fiksnih liturgijskih datuma poput Velike Gospe, Male Gospe, blagdana svetih Petra i Pavla i godišnjih hodočašća u Mariju Bistricu i Trsat. Ako medijska prisutnost prati te datume ciklički, mediji destinacije tretiraju kao događajne, a ne kao trajne tematske sadržaje. Razlika je fundamentalna za percepciju svetišta kao turističke destinacije u modernom smislu, jer trajno prisutna destinacija gradi imidž i brend, a događajno prisutna ostaje unutar folklorne i kalendarske svijesti publike. Teorijski, Katić i Klarin (2024) dokumentiraju napetost između svetišta kao godišnjeg događaja i svetišta kao stalne turističke atrakcije, što omogućuje klasifikaciju hrvatskih svetišta po toj dimenziji kao vrijedan empirijski doprinos.</p>
</section>
</section>
</section>
<section id="podaci-i-metode" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Podaci i metode</h1>
<section id="istraživački-dizajn" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="istraživački-dizajn"><span class="header-section-number">3.1</span> Istraživački dizajn</h2>
<p>Rad se temelji na kvantitativnoj analizi medijskog sadržaja (Krippendorff, 2018) povezanoj s teorijom uokvirivanja (Entman, 1993) i metodom računalnog modeliranja tema (Roberts i sur., 2014). Cilj je rekonstruirati medijsku reprezentaciju hrvatskih religijsko-turističkih odredišta u digitalnom medijskom prostoru u razdoblju od siječnja 2021. do svibnja 2024. godine. Analitički pristup kombinira pet komponenti. Rječničko označavanje registara s padežnom pokrivenošću za hrvatski jezik daje primarnu klasifikaciju članaka. Hi-kvadrat dekompozicija s mjerom snage povezanosti testira vezu između destinacije i okvira. Multinomijalna logistička regresija provodi multivarijatnu kontrolu konfundirajućih efekata vremena, mjeseca, platforme objave i blagdanskog prozora. Strukturalni model tema služi za induktivnu validaciju rječničke klasifikacije. Naposljetku, dvostruko ručno kodiranje stratificiranog uzorka procjenjuje pouzdanost rječničkog označavanja. Jedinica analize je medijski članak, a svaki je članak pripisan jednoj od deset destinacija prema primarnom spomenu u tekstu.</p>
</section>
<section id="izvor-podataka-i-konstrukcija-korpusa" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="izvor-podataka-i-konstrukcija-korpusa"><span class="header-section-number">3.2</span> Izvor podataka i konstrukcija korpusa</h2>
<p>Podaci za ovaj rad potječu iz baze DigiKat. Riječ je o javno dostupnoj bazi medijskih objava o katoličkoj tematici u hrvatskom digitalnom prostoru, izgrađenoj u sklopu istoimenoga istraživačkog projekta Hrvatskoga katoličkog sveučilišta. Baza prikuplja sadržaj automatiziranim alatima u stvarnom vremenu i indeksira informativne portale, blogove, forume te javne objave na društvenim platformama poput Facebooka, X-a, Reddita, YouTubea i Instagrama. U inačici korištenoj u ovome radu obuhvaća više od 600 000 objava prikupljenih u razdoblju od 2021. do 2026. godine, s pretežnom koncentracijom u hrvatskome jeziku i na hrvatskom geografskom području. Cjelovita metodologija prikupljanja, popis varijabli i otvorena inačica podataka opisani su u projektnoj dokumentaciji (DigiKat, 2026).</p>
<p>Za potrebe ovog istraživanja iz baze DigiKat izdvojen je tematski podkorpus. Iz vremenskog raspona od siječnja 2021. do svibnja 2024. zadržani su članci koji u naslovu ili tekstu spominju neku od deset odabranih hrvatskih katoličkih destinacija. Pretraživanje toponima i pripadajućih pridjeva morfološki je osjetljivo i pokriva nominativ, genitiv, dativ, akuzativ, lokativ i instrumental hrvatskoga jezika. Time se istodobno hvataju različiti padežni i pridjevski oblici poput Marija Bistrica, Mariji Bistrici i bistrička, ili Sinj, Sinju i sinjska.</p>
<p>Pet destinacija ima toponime koji se često pojavljuju izvan religijsko-turističkog konteksta. Sinj redovito ulazi u sportske vijesti, Nin se preklapa s osobnim imenom Nina, a Solin, Krasno i Ludbreg ulaze u različite opće upotrebne fraze i nazive izvan svetišne tematike. Za te su destinacije primijenjena dodatna sadržajna ograničenja. Članak ulazi u podkorpus jedino ako uz toponim sadrži leksički znak iz neke od triju kontrolnih skupina, a to su religija, hodočašće i turizam. Time se osigurava da podkorpus obuhvaća isključivo članke koji o tim destinacijama govore u relevantnome sadržajnome kontekstu. Naknadna provjera u kojoj se isti sadržajni filter primjenjuje uniformno na svih deset destinacija ne mijenja sastav korpusa, što potvrđuje da inicijalna asimetrija postupka nije unijela nepravilnost u uzorak.</p>
<p>Nakon uklanjanja duplikata i standardnih medijskih elemenata poput autorskih rubrika i navigacijskih okvira te nakon filtriranja po duljini teksta i jeziku, analitički korpus zadržava 13 921 članak. Destinacije su unaprijed klasificirane u tri tipa. U skupinu nacionalnih marijanskih svetišta ulaze Sinj (4 044 članka), Marija Bistrica (3 018) i Trsat (1 695), ukupno 8 757 članaka. U skupinu lokalnih marijanskih svetišta ulaze Aljmaš (1 628), Voćin (1 093), Ludbreg (331), Krasno (230) i Vepric (188), ukupno 3 470 članaka. U skupinu nemarijanskih katoličkih svetišta ulaze Solin (851) i Nin (843), ukupno 1 694 članka.</p>
</section>
<section id="označavanje-registara" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="označavanje-registara"><span class="header-section-number">3.3</span> Označavanje registara</h2>
<p>Svaki je članak iz korpusa označen prema rječničkim tragovima šest registara. Rječnici su pripremljeni za hrvatski jezik i pokrivaju glavne padežne oblike pojmova. Religijski registar obuhvaća leksik svetišta, hodočašća, blagdana, biskupa, svećenika, Gospe, mise, križa, oltara, krunice i srodne riječi. Turistički registar obuhvaća turizam, destinaciju, posjetitelja, hotel, smještaj, sezonu, izlet, atrakciju i srodne pojmove. Memorijalni registar obuhvaća leksik žrtve, spomena, stradanja, masakra, prognanika, mučenika, Domovinskog rata, ratnog konteksta i komemoracije. Skandal-registar obuhvaća skandal, kontroverzu, optužbu, istragu i aferu. Posebna skupina toponimskih pojmova s pripadajućim pridjevima služi za prepoznavanje samoga spomena destinacije i ne ulazi izravno u klasifikaciju okvira.</p>
<p>Pravilo aktivacije registra binarno je. Registar se smatra aktivnim ako u tekstu članka postoji barem jedno podudaranje s bilo kojim leksemom iz pripadajuće rječničke skupine. Robusnost glavnih nalaza na ovaj prag testirana je provjerom u kojoj se prag postupno podiže na dva i tri podudaranja. Rezultati provjere pokazuju da glavna struktura okvira ostaje, no apsolutni se udjeli registara očekivano smanjuju s pooštravanjem praga. Sažetak tih provjera dostupan je u prilogu (Tablica S3).</p>
<p>Iz aktivnih registara u svakom članku izvedena je kategorička varijabla okvira članka. Pravila izvođenja slijede ustaljenu leksikografsku praksu (Pennebaker i sur., 2015; Stoll i sur., 2020). Kada članak istodobno aktivira religijski i turistički registar, a ne aktivira memorijalni ili skandal-registar, klasificira se kao mješoviti religijsko-turistički. Kada članak istodobno aktivira religijski i memorijalni registar, bez snažnih turističkih obilježja, klasificira se kao religijsko-memorijalni. Tako se dobiva šestočlana klasifikacija s kategorijama religijski isključivo, religijsko-turistički mješoviti, turistički isključivo, religijsko-memorijalni, religijski sa skandalom i turistički sa skandalom.</p>
<p>Pri primijenjenoj razini praga izolirane kategorije memorijalni isključivo i skandal isključivo praktički ne postoje u korpusu. Memorijalni se registar gotovo uvijek pojavljuje uz religijski, a skandal-registar gotovo nikada nije izoliran u sadržaju o katoličkim svetištima. Memorijalni je rječnik dodan u trenutnoj inačici rječničkoga aparata zato što su ranije analize ostavljale velik dio sadržaja o Voćinu nezadovoljavajuće klasificiranim. Cjelovit popis leksema po registru i kontrolne provjere padežne pokrivenosti dostupni su u prilogu.</p>
</section>
<section id="analitički-postupci" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="analitički-postupci"><span class="header-section-number">3.4</span> Analitički postupci</h2>
<p>Za testiranje povezanosti destinacije i okvira upotrijebljen je hi-kvadrat test nezavisnosti s pripadajućom mjerom snage povezanosti, Cramérovim <em>V</em> (Cramér, 1946). Cramérov <em>V</em> skalira efekt na raspon od nule do jedan i omogućuje supstantivnu interpretaciju neovisnu o veličini uzorka. Vrijednost nula označuje neovisnost varijabli, a vrijednost jedan savršenu povezanost. Pri interpretaciji veličine efekta oslanjamo se na Cohenove okvirne pragove (Cohen, 1988), prema kojima vrijednosti oko 0,1 pripadaju malenom efektu, oko 0,3 srednjem, a oko 0,5 velikom efektu. Pouzdanost točkovne procjene Cramérovog <em>V</em> dodatno je provjerena uzorkovanjem s ponavljanjem na razini članaka u 1 000 ponavljanja, čime se dobiva 95-postotni interval povjerenja. U dekompoziciji povezanosti korišteni su standardizirani reziduali za identifikaciju ćelija s nadprosječnim ili podprosječnim opažanjima u odnosu na pretpostavku nezavisnosti.</p>
<p>Za multivarijatnu kontrolu konfundirajućih efekata procijenjena je multinomijalna logistička regresija (Hosmer i sur., 2013). Ovisna varijabla u modelu je okvir članka, a referentna kategorija je religijski isključivo. Skup prediktora obuhvaća destinaciju, godinu, mjesec, platformu objave i indikator blagdanskoga prozora. U inicijalnoj specifikaciji modela istovremeno su bili uključeni destinacija i tip destinacije, no budući da je tip determinirana funkcija destinacije, te dvije varijable nisu zasebno identificirane u istom modelu. Glavna verzija modela u ovom radu izostavlja tip destinacije i procjenjuje destinacijsku strukturu izravno preko deset razina destinacijske varijable. Komplementarna specifikacija modela koja procjenjuje učinak na razini tipa destinacije, izostavljajući destinaciju kao prediktor, dostupna je u prilogu (Tablica S1, panel B). Jedinica analize u modelu jest medijski članak, a analitički uzorak za multinomijalnu regresiju obuhvaća 13 644 članka, jer su iz procjene izostavljeni rijetki okviri sa skandal-registrom (skupno 277 članaka) zbog nedovoljne brojnosti za pouzdanu identifikaciju koeficijenata. Multinomijalni logit poopćuje binarnu logističku regresiju na ovisnu varijablu s više od dvije kategorije. Za svaku ne-referentnu kategoriju procjenjuje se zaseban skup koeficijenata koji izražavaju logaritamske omjere šansi (engl. log-odds) u odnosu na referentnu kategoriju. Time se simultano kontroliraju svi prediktori u modelu. Standardne pogreške procijenjene su robusno na klastersku strukturu izvora (varijabla <em>FROM</em> u korpusu) primjenom HC1 ocjenitelja. Kvaliteta prilagodbe modela izvještava se kroz Akaikeov informacijski kriterij (Akaike, 1974).</p>
<p>Za induktivnu validaciju rječničke klasifikacije procijenjen je strukturalni model tema (Roberts i sur., 2014; Roberts, Stewart i Tingley, 2019). Model pretpostavlja da je svaki članak generiran kao mješavina latentnih tema te dopušta kovarijatne prediktore distribucije tema. Tekstualno je polje za modeliranje sažetak medijskoga spominjanja destinacije. Predobrada teksta obuhvaća snižavanje slovnoga registra uz hrvatsku lokalizaciju, uklanjanje hrvatskih zaustavnih riječi (lista <em>quanteda</em> paketa za hrvatski jezik, dopunjena s pedesetak projektnih izraza poput riječi <em>foto</em>, <em>video</em> i <em>autor</em> koje su tipične za medijski boilerplate), zadržavanje pojmova s minimalnom učestalošću od deset pojavljivanja u korpusu te uključivanje unigramskih i bigramskih oblika. Lemmatizacija nije primijenjena. Optimalan broj tema izabran je dijagnostikom logaritamske vjerodostojnosti na uzorku zadržanih dokumenata, uz kvalitativnu provjeru semantičke koherentnosti i ekskluzivnosti tema. Pritom se za karakterizaciju tema koristi mjera FREX, koja u jednu skalu kombinira frekvenciju riječi u temi i ekskluzivnost te riječi u odnosu na druge teme (engl. <em>frequency-exclusivity</em>; Bischof i Airoldi, 2012), zbog čega bolje identificira semantički obilježene riječi nego sama vjerojatnost pojavljivanja. Konvergentna valjanost rječničke i induktivne klasifikacije procijenjena je dvama pokazateljima. Prvi je udio članaka kojima dominantna tema pripada istoj registarskoj kategoriji kao i dominantni rječnički okvir. Drugi je prilagođeni Randov indeks (Hubert i Arabie, 1985), koji procjenjuje slaganje dviju klasifikacija korigirano za slaganje očekivano slučajem. Jedinica analize STM-a jest medijski članak, a model je procijenjen na cjelokupnom korpusu od 13 921 članka.</p>
<p>Za vanjsku validaciju rječničkoga označavanja provedeno je dvostruko ručno kodiranje stratificiranoga uzorka od 200 članaka, s 20 članaka po destinaciji. Kodirni list slijedi šestočlanu shemu okvira iz §3.3. Pouzdanost među koderima procijenit će se Cohenovim kappa indeksom (Cohen, 1960) i Krippendorffovom alfom (Krippendorff, 2004). Konačni rezultati pouzdanosti uvrstit će se u finalnu inačicu rada.</p>
</section>
</section>
<section id="rezultati" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Rezultati</h1>
<section id="tri-registra-umjesto-dva" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="tri-registra-umjesto-dva"><span class="header-section-number">4.1</span> Tri registra umjesto dva</h2>
<p>Distribucija šest okvira u korpusu od 13 921 članka prikazana je u Tablici 1. Religijski isključivo okvir najzastupljeniji je s 5 504 članaka (39,5 %), slijede religijsko-turistički mješoviti s 3 133 članaka (22,5 %), turistički isključivo s 2 904 članka (20,9 %) i religijsko-memorijalni s 2 103 članka (15,1 %). Dva preostala okvira koja uključuju skandal-registar skupno čine manje od dva posto korpusa, ukupno 277 članaka (2,0 %), što potvrđuje da skandalni diskurs u medijskoj pokrivenosti hrvatskih katoličkih odredišta u promatranom razdoblju nije strukturalno značajan.</p>
<div id="tbl-frame-distribution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frame-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Distribucija okvira u analitičkom korpusu.
</figcaption>
<div aria-describedby="tbl-frame-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Okvir</th>
<th><em>N</em></th>
<th>%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Religijski isključivo</td>
<td>5 504</td>
<td>39,5</td>
</tr>
<tr class="even">
<td>Religijsko-turistički mješoviti</td>
<td>3 133</td>
<td>22,5</td>
</tr>
<tr class="odd">
<td>Turistički isključivo</td>
<td>2 904</td>
<td>20,9</td>
</tr>
<tr class="even">
<td>Religijsko-memorijalni</td>
<td>2 103</td>
<td>15,1</td>
</tr>
<tr class="odd">
<td>Religijski sa skandalom</td>
<td>141</td>
<td>1,0</td>
</tr>
<tr class="even">
<td>Turistički sa skandalom</td>
<td>136</td>
<td>1,0</td>
</tr>
<tr class="odd">
<td>Ukupno</td>
<td>13 921</td>
<td>100,0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Glavni teorijski značaj nalaza leži u petnaestpostotnom udjelu memorijalnog registra. Studije medijatizacije religije u hrvatskom kontekstu (Pavić, Kurbanović i Levak, 2017; Marinović Jerolimov, 2014) tipično konceptualiziraju medijski diskurs o katoličkim svetištima kroz duhovno-kulturni dvojac, dok teorije religijskog turizma operacionaliziraju isti prostor kroz dijadu religiozno-turističko (Griffin i Raj, 2018; Collins-Kreiner, 2020). Ni jedan ni drugi pristup ne predviđa zaseban memorijalni registar. Naš nalaz pokazuje da gotovo svaki sedmi članak u korpusu hrvatske medijske pokrivenosti katoličkih odredišta operira u jeziku spomena, žrtve i kolektivne traume. Riječ je o registru koji se preklapa s religijskim, ali se ne svodi na njega. Empirijski je riječ o linearnoj kombinaciji religijskog i memorijalnog leksika koji u mješovitim slučajevima zadržava liturgijski okvir, ali ga semantički preplavljuje sjećanjem.</p>
<p>Hi-kvadrat test nezavisnosti potvrđuje statistički značajnu povezanost destinacije i okvira (χ²(45) = 1 757,4, <em>p</em> &lt; 0,001, Cramérov <em>V</em> = 0,159). Procjena Cramérovog <em>V</em> dobivena uzorkovanjem s ponavljanjem u 1 000 replikacija centrirana je oko 0,161 s 95-postotnim intervalom povjerenja od 0,152 do 0,169. Točkovna se procjena, dakle, nalazi unutar uskoga intervala koji prema Cohenovim okvirnim pragovima čvrsto pripada području maloga efekta. Destinacije se međusobno razlikuju u distribuciji okvira, ali okvirna kompozicija nije dominantno determinirana destinacijom. Znatan dio varijacije proizlazi iz unutar-destinacijske heterogenosti članaka.</p>
<p>Multinomijalna logistička regresija s kontrolom za godinu, mjesec, platformu i blagdanski prozor (AIC = 33 087) potvrđuje da povezanost destinacije i okvira opstaje i nakon multivarijatne kontrole konfundirajućih varijabli. Standardne pogreške procijenjene su robusno na klastersku strukturu izvora, čime se izbjegavaju lažno uske intervalne procjene koje bi proizašle iz pretpostavke neovisnih opažanja. Potpuna tablica koeficijenata dostupna je u prilogu (Tablica S1). Glavni supstantivni nalaz multivarijatnoga modela jest da se destinacije Voćin i Marija Bistrica izdvajaju izrazito povišenim logaritamskim omjerima šansi za religijsko-memorijalni okvir, dok destinacije Trsat, Vepric i Krasno pokazuju izrazito snižene omjere za isti okvir. Za turistički isključivo okvir, najsnažnije snižene omjere bilježe Vepric i Ludbreg, a najviše Krasno i Nin. Komplementarna analiza na razini tipa destinacije pokazuje da nacionalna marijanska svetišta i nemarijanska odredišta imaju značajno snižene omjere šansi za religijsko-memorijalni okvir u odnosu na lokalna marijanska svetišta. Ti su nalazi dosljedni s opisnim obrascem koji se detaljnije razlaže u §4.2.</p>
</section>
<section id="geografija-memorijalnog-okvira" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="geografija-memorijalnog-okvira"><span class="header-section-number">4.2</span> Geografija memorijalnog okvira</h2>
<p>Memorijalni se registar pojavljuje u znatnoj mjeri u svim trima tipovima odredišta, ali s heterogenim intenzitetom unutar pojedinih lokaliteta. U Tablici 2 prikazani su udjeli okvira po tipu odredišta. Lokalna marijanska svetišta nose najveće memorijalno opterećenje s 22,9 % članaka u religijsko-memorijalnom okviru, nacionalna srednje s 13,1 %, a nemarijanska najmanje s 9,4 %. Suprotno tom obrascu, nemarijanska odredišta vode u turističkom okviru s 29,4 % i nadvisuju ostale tipove za približno sedam do jedanaest postotnih bodova. Religijski isključivo okvir izrazito dominira na nacionalnim marijanskim svetištima (43,5 %), s manjim udjelom na lokalnim marijanskim (31,5 %) i nemarijanskim (35,5 %) svetištima. Mješoviti religijsko-turistički okvir približno je ravnomjerno raspoređen među tipovima i kreće se između 19,7 % i 23,5 %, što sugerira da je miješanje religijskoga i turističkog jezika strukturna karakteristika hrvatskoga medijskog diskursa o svetištima neovisno o tipu odredišta.</p>
<div id="tbl-frame-by-type" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frame-by-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Distribucija okvira po tipu odredišta. Postoci su izračunati po retku. Iz tablice su izostavljena dva okvira sa skandal-registrom zbog niske ukupne zastupljenosti, pa retci ne moraju zbrojiti točno na 100 posto.
</figcaption>
<div aria-describedby="tbl-frame-by-type-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 25%">
<col style="width: 18%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Tip odredišta</th>
<th style="text-align: right;">Religijski isključivo (%)</th>
<th style="text-align: right;">Religijsko-turistički mješoviti (%)</th>
<th style="text-align: right;">Turistički isključivo (%)</th>
<th style="text-align: right;">Religijsko-memorijalni (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nacionalno marijansko</td>
<td style="text-align: right;">43,5</td>
<td style="text-align: right;">23,5</td>
<td style="text-align: right;">18,5</td>
<td style="text-align: right;">13,1</td>
</tr>
<tr class="even">
<td>Lokalno marijansko</td>
<td style="text-align: right;">31,5</td>
<td style="text-align: right;">19,7</td>
<td style="text-align: right;">22,6</td>
<td style="text-align: right;">22,9</td>
</tr>
<tr class="odd">
<td>Nemarijansko</td>
<td style="text-align: right;">35,5</td>
<td style="text-align: right;">23,1</td>
<td style="text-align: right;">29,4</td>
<td style="text-align: right;">9,4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pažljivija dekompozicija na razini pojedine destinacije, prikazana u Tablici 3, otkriva da je memorijalni registar široko prisutan u korpusu, ali da postoji samo jedna destinacija s izrazitim odstupanjem od korpusne razine. Voćin bilježi 42,0 % članaka u religijsko-memorijalnom okviru, što je gotovo trostruko više od korpusnoga prosjeka. Sva ostala odredišta kreću se unutar relativno uskoga raspona od 6,5 % do 19,9 % memorijalnoga udjela, pri čemu Aljmaš (14,6 %), Marija Bistrica (14,7 %) i Sinj (14,5 %) imaju gotovo identične proporcije, koje se približavaju korpusnom prosjeku. Sinj se pritom ističe apsolutnim brojem članaka u memorijalnom okviru, jer njegov visok ukupni volumen u korpusu rezultira s 586 memorijalnih članaka, što je čak 27,9 % svih memorijalnih članaka u korpusu. Voćin slijedi s 459 memorijalnih članaka (21,8 % memorijalnoga ukupnog), a Marija Bistrica s 444 članaka (21,1 %).</p>
<div id="tbl-memorial-by-dest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-memorial-by-dest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Memorijalni okvir po destinaciji. Udio u memorijalnom korpusu sumira na 100 posto.
</figcaption>
<div aria-describedby="tbl-memorial-by-dest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Destinacija</th>
<th>Tip</th>
<th style="text-align: right;"><em>N</em> ukupno</th>
<th style="text-align: right;"><em>N</em> memorijalnih</th>
<th style="text-align: right;">Memorijalnih (%)</th>
<th style="text-align: right;">Udio u memorijalnom korpusu (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Voćin</td>
<td>lokalno marijansko</td>
<td style="text-align: right;">1 093</td>
<td style="text-align: right;">459</td>
<td style="text-align: right;">42,0</td>
<td style="text-align: right;">21,8</td>
</tr>
<tr class="even">
<td>Ludbreg</td>
<td>lokalno marijansko</td>
<td style="text-align: right;">331</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">19,9</td>
<td style="text-align: right;">3,1</td>
</tr>
<tr class="odd">
<td>Marija Bistrica</td>
<td>nacionalno marijansko</td>
<td style="text-align: right;">3 018</td>
<td style="text-align: right;">444</td>
<td style="text-align: right;">14,7</td>
<td style="text-align: right;">21,1</td>
</tr>
<tr class="even">
<td>Aljmaš</td>
<td>lokalno marijansko</td>
<td style="text-align: right;">1 628</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">14,6</td>
<td style="text-align: right;">11,3</td>
</tr>
<tr class="odd">
<td>Sinj</td>
<td>nacionalno marijansko</td>
<td style="text-align: right;">4 044</td>
<td style="text-align: right;">586</td>
<td style="text-align: right;">14,5</td>
<td style="text-align: right;">27,9</td>
</tr>
<tr class="even">
<td>Solin</td>
<td>nemarijansko</td>
<td style="text-align: right;">851</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">10,6</td>
<td style="text-align: right;">4,3</td>
</tr>
<tr class="odd">
<td>Vepric</td>
<td>lokalno marijansko</td>
<td style="text-align: right;">188</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">10,1</td>
<td style="text-align: right;">0,9</td>
</tr>
<tr class="even">
<td>Nin</td>
<td>nemarijansko</td>
<td style="text-align: right;">843</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">8,3</td>
<td style="text-align: right;">3,3</td>
</tr>
<tr class="odd">
<td>Trsat</td>
<td>nacionalno marijansko</td>
<td style="text-align: right;">1 695</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">6,9</td>
<td style="text-align: right;">5,6</td>
</tr>
<tr class="even">
<td>Krasno</td>
<td>lokalno marijansko</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">6,5</td>
<td style="text-align: right;">0,7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Iz toga slijedi važna konceptualna distinkcija. Memorijalni registar nije obilježje malenoga skupa specijaliziranih lokaliteta, nego je strukturni element hrvatske medijske pokrivenosti katoličkih odredišta u cjelini. Otprilike svaki sedmi članak na nacionalnim marijanskim svetištima ulazi u memorijalni okvir, što ukazuje da svetišta poput Marije Bistrice i Sinja u hrvatskim medijima nisu isključivo prostori liturgije, nego i prostori spomena. Unutar te široke raspodjele Voćin se izdvaja kao kvalitativno različit slučaj. Stupanj memorijalne saturacije sadržaja o Voćinu odražava specifičnu povijest mjesta. U Voćinu je 13. prosinca 1991. godine počinjen masakr nad osamnaest civila i razorena je obnovljena marijanska crkva sv. Roka. Voćinska se medijska prisutnost u promatranom razdoblju zato u znatnom dijelu konstituira upravo kao prostor sjećanja na ratno stradanje, a marijanski blagdani vezani uz Voćin redovito aktiviraju leksik žrtve i komemoracije.</p>
<p>Drugim riječima, broj članaka u religijsko-memorijalnom okviru izvan Voćina i Aljmaša iznosi 1 407 od ukupnih 2 103, odnosno 66,9 % memorijalnoga korpusa. Memorijalni registar dakle nije reduktibilan ni na geografiju Domovinskog rata ni na malen broj specijaliziranih svetišta, nego predstavlja široko rasprostranjen sloj hrvatskoga medijskog diskursa o katoličkim odredištima u kojem se religijska kalendarska prisutnost redovito spaja sa spomenom, žrtvom ili komemorativnom funkcijom. Voćin je pritom gotovo paradigmatski slučaj u kojem ratna povijest mjesta nadjačava sve druge dimenzije medijske reprezentacije, ali nije generička kategorija u koju bi se mogli svrstati i drugi lokaliteti. Implikacije te raspodjele za teoriju medijatizacije katolicizma u poslijeratnim društvima razmatraju se u §5.</p>
</section>
<section id="sec-orthogonality" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-orthogonality"><span class="header-section-number">4.3</span> Konvergentna validnost rječničkih kategorija i induktivnih tema</h2>
<p>Kako bismo provjerili je li registarska klasifikacija iz §4.1 robusna na izbor metodološkog pristupa, procijenili smo strukturalni model tema na korpusu od 13 921 članka. Specifikacija prevalencije tema preuzima istu prediktorsku strukturu kao multinomijalna regresija u §4.1 i obuhvaća destinaciju, tip destinacije, prirodni splajn godine i indikator blagdanskog prozora. Optimalan broj tema <em>K</em> odabran je dijagnostikom logaritamske vjerodostojnosti na uzorku zadržanih dokumenata, pri čemu je u uzorku zadržano 10 % korpusa. Pretraženi raspon obuhvaća jedanaest vrijednosti <em>K</em> iz skupa 5, 7, 9, 10, 12, 15, 18, 20, 25, 30 i 35.</p>
<p>Krivulja logaritamske vjerodostojnosti dostiže maksimum pri <em>K</em> = 30 (−6,663), s blagim padom pri <em>K</em> = 35 (−6,668) te nižim vrijednostima pri <em>K</em> = 25 (−6,706) i <em>K</em> = 20 (−6,797). To potvrđuje da je <em>K</em> = 30 lokalni optimum unutar pretraženog raspona, a ne rubna vrijednost koja bi otvarala sumnju da optimalna konfiguracija leži iznad pretrage. Dijagnostička krivulja izbora <em>K</em> prikazana je u prilogu kao Slika S1. Kontrolne provjere konvergencije, izostanka raspada tema, izostanka dominantne teme i pokrivenosti korpusa ocijenjene su pozitivno. Minimalna čistoća tema bilježi se kao kontrolno upozorenje pri 36,9 % za temu T23 (ninski turistički klaster) i ne utječe na supstantivnu interpretaciju.</p>
<p>Topičku strukturu modela najbolje opisuju tri tipa tema, sažeto prikazana u Tablici 4. Čisto religijske teme broje šest jedinica i obuhvaćaju devocijski leksik, biskupske i franjevačke glasove te liturgijske događaje na nacionalnoj razini. Tema T15 prikazuje bistrička proštenja, tema T16 splitsko-makarsko episkopalno javljanje, tema T21 franjevački red kroz glas fra Zvjezdana Linića, a tema T28 godišnje obljetnice blaženog Alojzija Stepinca. Čisto turistička tema zastupljena je jednom jedinicom u modelu. Riječ je o temi T14 s leksikom odmora, wellnessa, spa-a, resorta i noćenja, koja s udjelom turističkog rječničkog registra od 92,6 % dominantno pokriva velebitsko-krašnjarski rekreacijski sadržaj. Mjesto-događajni klasteri čine većinu modela i obuhvaćaju preostale 23 teme. Te teme opisuju specifične sprege destinacije i događaja, poput političkog konteksta Sinjske Alke (T11 s riječima alku, alkarskog, milanović, sinjsku i boban), klapskog pjevanja pred čudotvornom slikom Sinjske Gospe (T13), zavjetnih dolazaka vatrogasaca i policije u Mariju Bistricu (T6), Eucharistijskog svetišta u Ludbregu (T25), solinskog festivala na Gradini (T17) i ninskog turističkog ekosustava (T23). Cjelovita lista tema s FREX vokabularom dostupna je u prilogu (Tablica S2).</p>
<div id="tbl-stm-types" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stm-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Tematska struktura strukturalnog modela tema pri <em>K</em> = 30. Prikazana su tri tipa tema.
</figcaption>
<div aria-describedby="tbl-stm-types-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 11%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Tematski tip</th>
<th style="text-align: right;"><em>N</em> tema</th>
<th>Reprezentativne teme i njihov FREX vokabular</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Čisto religijske</td>
<td style="text-align: right;">6</td>
<td>T15 (bistričke, nacionalno, rođacima), T27 (velike, gospe, blagdana), T30 (misa, uživo, krunica)</td>
</tr>
<tr class="even">
<td>Čisto turistička</td>
<td style="text-align: right;">1</td>
<td>T14 (odmor, wellness, spa, resort, noćenje)</td>
</tr>
<tr class="odd">
<td>Mjesto-događajni klasteri</td>
<td style="text-align: right;">23</td>
<td>T11 sa Sinjskom Alkom (alku, alkarskog, sinjsku), T25 s ludbreškom Predragocjenom Krvi (krvi, kristove, ludbregu), T8 s Požeškom biskupijom (voćinske, požeške, škvorčević, aljmaš), <strong>T19 s ratnim spomenom (selu, ratu, zločina, počast, žrtvama)</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Strukturalni model tema neovisno surfacira temu T19 s FREX vrhovima selu, ratu, zločina, počast i žrtvama, koja djeluje kao distinktivno memorijalna. Točno 60,8 % članaka u kojima je T19 modalna tema klasificirano je rječnički u religijsko-memorijalni okvir, što je daleko najveći takav udio među svim temama. Komplementarna tema T8, definirana FREX-vrhovima voćinske, požeške, voćinskoj, škvorčević i aljmaš, opisuje diskurs Požeške biskupije koji obuhvaća Voćin i Aljmaš, uz visok memorijalni udio od 40,1 %. Te dvije teme zajedno predstavljaju najsnažnije induktivne tragove ratno-spomenskog sadržaja u korpusu.</p>
<p>No važno je razumjeti distribucijski opseg tih dvaju tematskih klastera u odnosu na ukupni memorijalni korpus. Tema T19 obuhvaća svega 301 članak u kojima je modalna tema, što čini 2,2 % korpusa. Od 2 103 članaka koji su rječnički klasificirani kao religijsko-memorijalni, samo njih 183 (8,7 %) ima T19 kao modalnu temu. Slično, tema T8 modalna je za 661 članak u korpusu, od kojih je 265 u memorijalnom okviru, što čini 12,6 % memorijalnoga korpusa. Modalna distribucija tema unutar memorijalnoga okvira upućuje na to da se memorijalni leksik javlja u sklopu raznolikih tematskih konteksta. Najveći udio memorijalnih članaka pripada temi T6, koja opisuje zavjetne dolaske vatrogasaca i policije u Mariju Bistricu i prečesto se javlja kao kontekst u kojem se komemorativno spomenu poginuli pripadnici tih struktura (12,7 % memorijalnoga korpusa). Slijede T8 s Požeškom biskupijom (12,6 %) i T19 s ratnim spomenom (8,7 %). Daljnji znatni udjeli javljaju se u temi T11 koja opisuje politički kontekst Sinjske Alke (8,2 %) i u temi T24 koja pokriva opću sinjsku tematiku (6,9 %).</p>
<p>Iz toga slijedi da rječnička klasifikacija prepoznaje memorijalni leksik kao linearno svojstvo članka, dok strukturalni model tema isti taj leksik raspodjeljuje u tematski različite klastere. Sveukupno slaganje rječničke i induktivne klasifikacije ostaje nisko. Udio članaka kojima dominantna tema pripada istoj registarskoj kategoriji kao i dominantni rječnički okvir iznosi 54,6 % i time prelazi unaprijed definirani prag od 50 %. Prilagođeni Randov indeks iznosi 0,018, što je praktički nula. Slaganje od 54,6 % pokazuje da među trideset tema postoje one čiji se modalni rječnički okvir podudara s dominantnim registrom, osobito čisto religijske teme i čisto turistička tema. Indeks blizak nuli pokazuje da takva preklapanja ne formiraju strukturno slaganje između dviju klasifikacija na razini cijeloga korpusa. Drugim riječima, dvije metode mjere strukturno različite osi sadržaja. Rječnik mjeri leksički registar i odgovara na pitanje kategoriziraju li riječi u članku duhovni, turistički, memorijalni ili skandalni jezični kod. Strukturalni model tema mjeri mjesto-događajnu kookurenciju i odgovara na pitanje koji se akteri, lokaliteti i događaji pojavljuju zajedno u istom članku.</p>
<p>Ova dijagnostika nije slabost modela, nego empirijsko obrazloženje zašto su dvije metode komplementarne, a ne konkurentne. Rječnička klasifikacija identificira memorijalni registar kao linearnu kombinaciju dvaju leksičkih kodova, religijskog i memorijalnog. Strukturalni model tema identificira distinktivno memorijalne tematske klastere u T19 i T8, ali ostatak memorijalnoga sadržaja raspršuje po tematski raznolikim kontekstima. Dvostruka detekcija memorijalnoga signala u oba sustava klasifikacije, premda u različitim opsezima, čini glavni nalaz ovoga rada robusnim u odnosu na izbor klasifikacijske metode. Da je memorijalni registar artefakt rječnika, strukturalni model tema ne bi reproducirao ratno-spomensku temu kao distinktivno memorijalnu (T19, 60,8 % memorijalnih u svojoj temi). Da je artefakt induktivnoga modela, ne bi se ponavljao u rječničkoj registarskoj distribuciji s petnaestpostotnom ukupnom razinom. Komplementarnost dviju metoda eliminira oba metodološka prigovora.</p>
</section>
<section id="stabilnost-u-razdoblju-nakon-pandemije" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="stabilnost-u-razdoblju-nakon-pandemije"><span class="header-section-number">4.4</span> Stabilnost u razdoblju nakon pandemije</h2>
<p>Da bismo testirali sugeriraju li podaci sustavni vremenski pomak okvirne distribucije, procijenili smo regresijski model udjela triju glavnih okvira u funkciji godine, uz fiksne efekte destinacije i fiksne efekte godine. Test je usmjeren na dvije moguće interpretacije. Prva je pretpostavka post-pandemijskog povratka turističkog okvira koji bi mogao proizaći iz masovnih kampanja revitalizacije turizma 2022. i 2023. godine. Druga je pretpostavka post-pandemijskog jačanja religijskoga okvira do kojeg bi moglo doći zbog oporavka crkvenih okupljanja i fizičkog vraćanja vjernika u svetišta. Specifikacija s godinom kao faktorskim prediktorom dopušta odvojeno testiranje tih obrazaca, izbjegavajući linearnu pretpostavku koja bi maskirala nelinearne dinamike u kratkom petogodišnjem rasponu. Tip destinacije izostavljen je iz prediktorskoga skupa jer je determinirana funkcija destinacije i nije zasebno identificiran kada su uključeni destinacijski fiksni efekti. Standardne pogreške robusno su procijenjene na klastersku strukturu destinacija. Jedinica analize jest destinacijsko-godišnja ćelija, a panel sadrži 37 ćelija, jer u trima slučajevima maleni broj članaka u pojedinim destinacijama nije dovoljno popunio cijelu godinu.</p>
<p>Test zajedničke značajnosti godišnjih fiksnih efekata daje statističku potporu interpretaciji o stabilnosti distribucije okvira. Za udio turističkoga okvira <em>F</em>-statistika iznosi 1,20 (df = 3, 24; <em>p</em> = 0,33). Za udio religijskoga okvira <em>F</em> = 0,83 (<em>p</em> = 0,49). Za udio memorijalnoga okvira <em>F</em> = 1,85 (<em>p</em> = 0,17). U sva tri slučaja godišnji fiksni efekti zajednički ne dosežu prag značajnosti. Drugim riječima, distribucija okvira u razdoblju od siječnja 2021. do svibnja 2024. ne pokazuje nijedan statistički potvrđen vremenski obrazac, ni prema turistifikaciji ni prema religijskoj retradicionalizaciji.</p>
<p>Korpusno-izvagani godišnji prosjeci, prikazani u Tablici 5, podupiru nalaz na deskriptivnoj razini. Udio religijskog isključivo okvira raste s 36,2 % u 2021. na 48,4 % u 2024. godini, no zadnji broj treba čitati s oprezom jer 2024. obuhvaća samo članke objavljene do svibnja te godine i u korpusu sudjeluje sa svega 62 članka. Iz istog razloga vidljiv pad udjela memorijalnog okvira na 3,2 % u 2024. godini ne treba interpretirati kao supstantivnu promjenu, nego kao statistički šum proizašao iz vrlo male pod-uzorne brojnosti. U ostalim trima cijelim godinama, koje zajedno obuhvaćaju 13 859 članaka, distribucija okvira zadržava stabilan profil unutar očekivanih oscilacija.</p>
<div id="tbl-yearly-shares" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-yearly-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Godišnji korpusno-izvagani udjeli triju glavnih okvira. Brojevi za 2024. godinu temelje se isključivo na članicima objavljenim do svibnja te godine i odražavaju malenu pod-uzornu brojnost.
</figcaption>
<div aria-describedby="tbl-yearly-shares-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 24%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Godina</th>
<th style="text-align: right;">Turistički udio</th>
<th style="text-align: right;">Religijski udio</th>
<th style="text-align: right;">Memorijalni udio</th>
<th style="text-align: right;"><em>N</em> članaka</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2021.</td>
<td style="text-align: right;">0,210</td>
<td style="text-align: right;">0,362</td>
<td style="text-align: right;">0,165</td>
<td style="text-align: right;">4 203</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022.</td>
<td style="text-align: right;">0,195</td>
<td style="text-align: right;">0,412</td>
<td style="text-align: right;">0,158</td>
<td style="text-align: right;">4 272</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023.</td>
<td style="text-align: right;">0,219</td>
<td style="text-align: right;">0,407</td>
<td style="text-align: right;">0,136</td>
<td style="text-align: right;">5 384</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024.</td>
<td style="text-align: right;">0,177</td>
<td style="text-align: right;">0,484</td>
<td style="text-align: right;">0,032</td>
<td style="text-align: right;">62</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Disagregirana usporedba pojedinih destinacija pokazuje da kada destinacijska razina pokazuje promjene, te promjene idu u različitim smjerovima i poništavaju se u korpusnom prosjeku. Udio religijski isključivo okvira porastao je za pet ili više postotnih bodova u Sinju, Krasnom, Vepricu, Mariji Bistrici i Aljmašu. Istodobno je pao u Trsatu, Ninu, Voćinu i Solinu, dok je Ludbreg zadržao stabilnu poziciju. Smjer promjene očito ovisi o destinaciji, a ne o sustavnom vremenskom obrascu, što isključuje interpretaciju u kojoj bi pandemija inducirala uniforman okvirni pomak.</p>
<p>Ovaj nalaz služi kao negativan dokaz u odnosu na obje izložene hipoteze. Post-pandemijska medijska komunikacija o hrvatskim katoličkim odredištima nije se, sustavno gledano, okrenula prema turističkom registru kako bi se moglo očekivati u kontekstu kampanja revitalizacije domaćeg turizma. Isto tako, nije zabilježeno sustavno jačanje religijskoga okvira koje bi se moglo pripisati postpandemijskom oporavku crkvenih okupljanja. Distribucija okvira u promatranom razdoblju ostaje strukturno stabilna, što memorijalnu razinu od 15 % iz §4.1 čini stabilnom karakteristikom medijskog diskursa o hrvatskim katoličkim svetištima, a ne tranzitnim pandemijskim artefaktom.</p>
</section>
</section>
<section id="rasprava" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Rasprava</h1>
<p>TBD</p>
</section>
<section id="zaključak" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Zaključak</h1>
<p>TBD</p>
</section>
<section id="literatura" class="level1 unnumbered">
<h1 class="unnumbered">Literatura</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>